# Generated by Django 3.2.7 on 2021-09-16 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0002_song_artists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='style',
            field=models.CharField(choices=[('R', 'Rap'), ('HP', 'Hip-hop'), ('P', 'Pop'), ('G', 'Gang'), ('DS', 'Diss'), ('C', 'Classical'), ('CO', 'Country'), ('ED', 'EDM'), ('M', 'Metal'), ('RB', 'R&B'), ('JZ', 'Jazz'), ('O', 'Oldies'), ('OT', 'Other')], default='OT', max_length=2),
        ),
    ]
