# Generated by Django 3.2.7 on 2021-09-17 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0004_alter_artist_style'),
        ('song', '0003_alter_song_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='style',
            field=models.CharField(choices=[('R', 'Rap'), ('HP', 'Hip-hop'), ('P', 'Pop'), ('C', 'Classical'), ('CO', 'Country'), ('ED', 'EDM'), ('M', 'Metal'), ('RB', 'R&B'), ('JZ', 'Jazz'), ('O', 'Oldies'), ('OT', 'Other')], default='OT', max_length=2),
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('number_of_songs', models.PositiveIntegerField()),
                ('duration', models.CharField(blank=True, max_length=20, null=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='artist.artist')),
            ],
        ),
        migrations.AddField(
            model_name='song',
            name='album',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='song.album'),
        ),
    ]
