# Generated by Django 3.2.7 on 2021-09-17 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0005_auto_20210917_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='cover',
        ),
        migrations.AlterField(
            model_name='song',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='song',
            name='lyrics',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='stream',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
