# Generated by Django 3.2.7 on 2021-09-17 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0006_auto_20210917_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='duration',
        ),
    ]
