# Generated by Django 3.2.7 on 2021-09-17 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0007_remove_album_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='number_of_songs',
        ),
    ]
