# Generated by Django 3.2.7 on 2021-09-17 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0008_remove_album_number_of_songs'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='uuid',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
