# Generated by Django 3.2.7 on 2021-09-17 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0007_remove_artist_top_track'),
        ('song', '0009_album_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='artists',
        ),
        migrations.AddField(
            model_name='song',
            name='artist',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='artist.artist'),
            preserve_default=False,
        ),
    ]
