# Generated by Django 3.2.7 on 2021-09-18 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0010_auto_20210917_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='play',
            field=models.URLField(max_length=300),
        ),
    ]
