# Generated by Django 3.2.7 on 2021-09-17 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0003_alter_song_style'),
        ('artist', '0002_alter_artist_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='top_track',
            field=models.ManyToManyField(blank=True, to='song.Song'),
        ),
    ]
