# Generated by Django 3.2.7 on 2021-09-17 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0003_alter_artist_top_track'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='style',
            field=models.CharField(choices=[('R', 'Rap'), ('HP', 'Hip-hop'), ('P', 'Pop'), ('C', 'Classical'), ('CO', 'Country'), ('ED', 'EDM'), ('M', 'Metal'), ('RB', 'R&B'), ('JZ', 'Jazz'), ('O', 'Oldies'), ('OT', 'Other')], default='OT', max_length=2),
        ),
    ]
