# Generated by Django 3.2.7 on 2021-09-17 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0006_alter_artist_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='top_track',
        ),
    ]
